# FLIPKART PRODUCT DATASET
# ANALYSIS.PY


# Purpose:
#   Analyze the cleaned Flipkart dataset generated by
#   data_cleaning.py

# Analysis included:
#   1. Dataset overview
#   2. Data quality
#   3. Category analysis
#   4. Price analysis
#   5. Discount analysis
#   6. Outlier analysis
#   7. Rating analysis
#   8. Correlation analysis
#   9. Brand analysis
#   10. Price-band analysis
#   11. Product filtering
#   12. Business insights
#   13. Export analysis results




# 1. IMPORT LIBRARIES


import os
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


warnings.filterwarnings("ignore")


# Display settings
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 150)
pd.set_option("display.max_rows", 100)
pd.set_option(
    "display.float_format",
    lambda x: f"{x:,.2f}"
)


# 2. CONFIGURATION


INPUT_FILE = os.path.join(
    "processed_data",
    "flipkart_cleaned.csv"
)

OUTPUT_FOLDER = "analysis_results"

os.makedirs(
    OUTPUT_FOLDER,
    exist_ok=True
)



# 3. LOAD CLEANED DATA


def load_data():

    if not os.path.exists(INPUT_FILE):

        raise FileNotFoundError(
            f"""
Cleaned dataset not found.

Expected file:
{INPUT_FILE}

First run:
python data_cleaning.py
"""
        )

    df = pd.read_csv(INPUT_FILE)

    print("=" * 70)
    print("DATASET LOADED")
    print("=" * 70)

    print(f"Rows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]:,}")

    return df



# 4. BASIC DATASET INFORMATION


def dataset_overview(df):

    print("\n")
    print("=" * 70)
    print("1. DATASET OVERVIEW")
    print("=" * 70)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    for column in df.columns:
        print(" -", column)

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 10 rows:")
    print(df.head(10))

    print("\nStatistical Summary:")
    print(df.describe(include="all").T)



# 5. DATA QUALITY ANALYSIS


def data_quality_analysis(df):

    print("\n")
    print("=" * 70)
    print("2. DATA QUALITY ANALYSIS")
    print("=" * 70)

    # Missing values
    missing = pd.DataFrame({
        "Missing_Count": df.isna().sum(),
        "Missing_Percentage": (
            df.isna().mean() * 100
        ).round(2)
    })

    missing = (
        missing[
            missing["Missing_Count"] > 0
        ]
        .sort_values(
            "Missing_Count",
            ascending=False
        )
    )

    print("\nMissing Values:")
    print(missing)

    # Duplicate rows
    duplicate_count = df.duplicated().sum()

    print(
        f"\nDuplicate rows: {duplicate_count:,}"
    )

    # Unique values
    print("\nUnique values:")
    print(df.nunique().sort_values(ascending=False))

    # Save quality report
    missing.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "missing_values.csv"
        )
    )



# 6. CATEGORY ANALYSIS


def category_analysis(df):

    print("\n")
    print("=" * 70)
    print("3. CATEGORY ANALYSIS")
    print("=" * 70)

    category_summary = (
        df.groupby("Category")
        .agg(

            Product_Count=(
                "Product Name",
                "count"
            ),

            Brand_Count=(
                "Brand",
                "nunique"
            ),

            Average_Price=(
                "Price",
                "mean"
            ),

            Median_Price=(
                "Price",
                "median"
            ),

            Minimum_Price=(
                "Price",
                "min"
            ),

            Maximum_Price=(
                "Price",
                "max"
            ),

            Total_Price=(
                "Price",
                "sum"
            ),

            Total_Original_Price=(
                "Original Prices",
                "sum"
            ),

            Average_Discount=(
                "Discount rates",
                "mean"
            ),

            Median_Discount=(
                "Discount rates",
                "median"
            ),

            Total_Discount=(
                "Discount_Amount",
                "sum"
            )
        )
        .reset_index()
        .round(2)
    )

    print("\nCategory Summary:")
    print(category_summary)

    # Save
    category_summary.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "category_summary.csv"
        ),
        index=False
    )

    
    # Visualization 1
    # Product count by category
   

    plt.figure(figsize=(11, 6))

    data = (
        category_summary
        .sort_values(
            "Product_Count"
        )
    )

    plt.barh(
        data["Category"],
        data["Product_Count"]
    )

    plt.title(
        "Product Count by Category"
    )

    plt.xlabel(
        "Number of Products"
    )

    plt.ylabel(
        "Category"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "01_product_count_category.png"
        ),
        dpi=300
    )

    plt.show()

    
    # Visualization 2
    # Average price by category
   

    plt.figure(figsize=(11, 6))

    data = (
        category_summary
        .sort_values(
            "Average_Price"
        )
    )

    plt.barh(
        data["Category"],
        data["Average_Price"]
    )

    plt.title(
        "Average Selling Price by Category"
    )

    plt.xlabel(
        "Average Price (₹)"
    )

    plt.ylabel(
        "Category"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "02_average_price_category.png"
        ),
        dpi=300
    )

    plt.show()

    
    # Visualization 3
    # Median price by category
   

    plt.figure(figsize=(11, 6))

    data = (
        category_summary
        .sort_values(
            "Median_Price"
        )
    )

    plt.barh(
        data["Category"],
        data["Median_Price"]
    )

    plt.title(
        "Median Selling Price by Category"
    )

    plt.xlabel(
        "Median Price (₹)"
    )

    plt.ylabel(
        "Category"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "03_median_price_category.png"
        ),
        dpi=300
    )

    plt.show()

    return category_summary



# 7. PRICE ANALYSIS


def price_analysis(df):

    print("\n")
    print("=" * 70)
    print("4. PRICE ANALYSIS")
    print("=" * 70)

    price_data = df.dropna(
        subset=["Price"]
    )

    print("\nPrice Statistics:")

    print(
        price_data["Price"].describe()
    )

    
    # Visualization 4
    # Price distribution
    

    plt.figure(figsize=(10, 6))

    sns.histplot(
        price_data["Price"],
        bins=50,
        kde=True
    )

    plt.xscale("log")

    plt.title(
        "Selling Price Distribution"
    )

    plt.xlabel(
        "Selling Price (₹, log scale)"
    )

    plt.ylabel(
        "Number of Products"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "04_price_distribution.png"
        ),
        dpi=300
    )

    plt.show()

   
    # Visualization 5
    # Price by category
   

    plt.figure(figsize=(12, 7))

    sns.boxplot(
        data=price_data,
        x="Category",
        y="Price"
    )

    plt.yscale("log")

    plt.title(
        "Selling Price Distribution by Category"
    )

    plt.xlabel("Category")
    plt.ylabel(
        "Selling Price (₹, log scale)"
    )

    plt.xticks(
        rotation=35,
        ha="right"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "05_price_by_category.png"
        ),
        dpi=300
    )

    plt.show()

    # Top expensive products
   

    top_expensive = (
        price_data
        .sort_values(
            "Price",
            ascending=False
        )
        [
            [
                "Category",
                "Product Name",
                "Price",
                "Original Prices",
                "Discount rates"
            ]
        ]
        .head(20)
    )

    print("\nTop 20 Expensive Products:")
    print(top_expensive)

    top_expensive.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "top_expensive_products.csv"
        ),
        index=False
    )


# 8. DISCOUNT ANALYSIS


def discount_analysis(df):

    print("\n")
    print("=" * 70)
    print("5. DISCOUNT ANALYSIS")
    print("=" * 70)

    discount_data = df.dropna(
        subset=["Discount rates"]
    )

    print("\nDiscount Statistics:")

    print(
        discount_data[
            "Discount rates"
        ].describe()
    )

    
    # Visualization 6
    # Discount distribution
   

    plt.figure(figsize=(10, 6))

    sns.histplot(
        discount_data["Discount rates"],
        bins=30,
        kde=True
    )

    plt.title(
        "Discount Rate Distribution"
    )

    plt.xlabel(
        "Discount Rate (%)"
    )

    plt.ylabel(
        "Number of Products"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "06_discount_distribution.png"
        ),
        dpi=300
    )

    plt.show()

    
    # Visualization 7
    # Discount by category
    

    plt.figure(figsize=(12, 7))

    sns.boxplot(
        data=discount_data,
        x="Category",
        y="Discount rates"
    )

    plt.title(
        "Discount Distribution by Category"
    )

    plt.xlabel("Category")
    plt.ylabel(
        "Discount Rate (%)"
    )

    plt.xticks(
        rotation=35,
        ha="right"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "07_discount_by_category.png"
        ),
        dpi=300
    )

    plt.show()

    
    # Category discount summary
   

    discount_summary = (
        discount_data
        .groupby("Category")
        ["Discount rates"]
        .agg(
            [
                "count",
                "mean",
                "median",
                "min",
                "max"
            ]
        )
        .round(2)
    )

    print(
        "\nDiscount Summary by Category:"
    )

    print(discount_summary)

    discount_summary.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "discount_summary.csv"
        )
    )



# 9. ORIGINAL PRICE VS SELLING PRICE


def price_discount_relationship(df):

    print("\n")
    print("=" * 70)
    print("6. PRICE AND DISCOUNT RELATIONSHIP")
    print("=" * 70)

    data = df.dropna(
        subset=[
            "Price",
            "Original Prices"
        ]
    ).copy()

   
    # Visualization 8
    # Original vs selling price
    

    plt.figure(figsize=(10, 7))

    sns.scatterplot(
        data=data,
        x="Original Prices",
        y="Price",
        hue="Category",
        alpha=0.6
    )

    max_price = max(
        data["Original Prices"].max(),
        data["Price"].max()
    )

    plt.plot(
        [0, max_price],
        [0, max_price],
        linestyle="--"
    )

    plt.xscale("log")
    plt.yscale("log")

    plt.title(
        "Original Price vs Selling Price"
    )

    plt.xlabel(
        "Original Price (₹)"
    )

    plt.ylabel(
        "Selling Price (₹)"
    )

    plt.legend(
        bbox_to_anchor=(1.02, 1),
        loc="upper left"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "08_original_vs_selling_price.png"
        ),
        dpi=300
    )

    plt.show()

    # 
    # Visualization 9
    # Price vs discount
    # 

    plt.figure(figsize=(10, 7))

    sns.scatterplot(
        data=data,
        x="Price",
        y="Discount rates",
        hue="Category",
        alpha=0.6
    )

    plt.xscale("log")

    plt.title(
        "Selling Price vs Discount Rate"
    )

    plt.xlabel(
        "Selling Price (₹, log scale)"
    )

    plt.ylabel(
        "Discount Rate (%)"
    )

    plt.legend(
        bbox_to_anchor=(1.02, 1),
        loc="upper left"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "09_price_vs_discount.png"
        ),
        dpi=300
    )

    plt.show()



# 10. OUTLIER ANALYSIS


def outlier_analysis(df):

    print("\n")
    print("=" * 70)
    print("7. OUTLIER ANALYSIS")
    print("=" * 70)

    results = []

    for category, group in df.groupby(
        "Category"
    ):

        prices = group[
            "Price"
        ].dropna()

        if len(prices) == 0:
            continue

        q1 = prices.quantile(0.25)
        q3 = prices.quantile(0.75)

        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outliers = (
            (prices < lower) |
            (prices > upper)
        )

        results.append({
            "Category": category,
            "Q1": q1,
            "Q3": q3,
            "IQR": iqr,
            "Lower_Bound": lower,
            "Upper_Bound": upper,
            "Outlier_Count": int(
                outliers.sum()
            )
        })

    outlier_df = pd.DataFrame(
        results
    ).round(2)

    print("\nPrice Outliers by Category:")
    print(outlier_df)

    outlier_df.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "price_outliers.csv"
        ),
        index=False
    )

    # 
    # Visualization 10
    # 

    plt.figure(figsize=(11, 6))

    data = (
        outlier_df
        .sort_values(
            "Outlier_Count"
        )
    )

    plt.barh(
        data["Category"],
        data["Outlier_Count"]
    )

    plt.title(
        "Price Outliers by Category (IQR Method)"
    )

    plt.xlabel(
        "Number of Outliers"
    )

    plt.ylabel(
        "Category"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "10_price_outliers.png"
        ),
        dpi=300
    )

    plt.show()

    # 
    # Extreme products
    # 

    top_expensive = (
        df.dropna(
            subset=["Price"]
        )
        .sort_values(
            "Price",
            ascending=False
        )
        [
            [
                "Category",
                "Product Name",
                "Price",
                "Original Prices",
                "Discount rates"
            ]
        ]
        .head(20)
    )

    print(
        "\nTop Extreme-Price Products:"
    )

    print(top_expensive)



# 11. RATING ANALYSIS


def rating_analysis(df):

    if "Ratings" not in df.columns:

        print(
            "\nRatings column not available."
        )

        return

    print("\n")
    print("=" * 70)
    print("8. RATING ANALYSIS")
    print("=" * 70)

    rating_df = df.dropna(
        subset=["Ratings"]
    ).copy()

    if rating_df.empty:

        print(
            "No rating data available."
        )

        return

    # 
    # Rating summary
    # 

    rating_summary = (
        rating_df
        .groupby("Category")
        ["Ratings"]
        .agg(
            [
                "count",
                "mean",
                "median",
                "min",
                "max"
            ]
        )
        .round(2)
    )

    print("\nRating Summary:")
    print(rating_summary)

    rating_summary.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "rating_summary.csv"
        )
    )

    # 
    # Visualization 11
    # Rating boxplot
    # 

    plt.figure(figsize=(9, 6))

    sns.boxplot(
        data=rating_df,
        x="Category",
        y="Ratings"
    )

    plt.title(
        "Ratings Distribution by Category"
    )

    plt.xlabel("Category")
    plt.ylabel("Rating")

    plt.xticks(
        rotation=35,
        ha="right"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "11_rating_by_category.png"
        ),
        dpi=300
    )

    plt.show()

    # 
    # Visualization 12
    # Overall rating distribution
    # 

    plt.figure(figsize=(9, 6))

    sns.histplot(
        rating_df["Ratings"],
        bins=20,
        kde=True
    )

    plt.title(
        "Overall Rating Distribution"
    )

    plt.xlabel("Rating")
    plt.ylabel(
        "Number of Products"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "12_rating_distribution.png"
        ),
        dpi=300
    )

    plt.show()

    # 
    # Visualization 13
    # Price vs rating
    # 

    rating_price = rating_df.dropna(
        subset=[
            "Price",
            "Ratings"
        ]
    )

    plt.figure(figsize=(10, 6))

    sns.scatterplot(
        data=rating_price,
        x="Price",
        y="Ratings",
        hue="Category",
        alpha=0.65
    )

    plt.xscale("log")

    plt.title(
        "Selling Price vs Rating"
    )

    plt.xlabel(
        "Selling Price (₹, log scale)"
    )

    plt.ylabel("Rating")

    plt.legend(
        bbox_to_anchor=(1.02, 1),
        loc="upper left"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "13_price_vs_rating.png"
        ),
        dpi=300
    )

    plt.show()



# 12. CORRELATION ANALYSIS


def correlation_analysis(df):

    print("\n")
    print("=" * 70)
    print("9. CORRELATION ANALYSIS")
    print("=" * 70)

    possible_columns = [
        "Price",
        "Original Prices",
        "Discount rates",
        "Discount_Amount",
        "Discount_Rate_Calculated",
        "Ratings"
    ]

    numeric_columns = [
        column
        for column in possible_columns
        if column in df.columns
    ]

    corr = df[
        numeric_columns
    ].corr(
        numeric_only=True
    )

    print("\nCorrelation Matrix:")
    print(corr.round(3))

    corr.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "correlation_matrix.csv"
        )
    )

    # 
    # Visualization 14
    # 

    plt.figure(figsize=(10, 7))

    sns.heatmap(
        corr,
        annot=True,
        fmt=".2f",
        cmap="coolwarm",
        center=0
    )

    plt.title(
        "Numeric Correlation Matrix"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "14_correlation_matrix.png"
        ),
        dpi=300
    )

    plt.show()

    # 
    # Correlation by category
    # 

    print(
        "\nCorrelation by Category:"
    )

    for category, group in df.groupby(
        "Category"
    ):

        available = [
            column
            for column in numeric_columns
            if column in group.columns
        ]

        if len(available) < 2:
            continue

        category_corr = (
            group[available]
            .corr()
            .round(3)
        )

        print(
            f"\n--- {category} ---"
        )

        print(category_corr)



# 13. BRAND ANALYSIS


def brand_analysis(df):

    print("\n")
    print("=" * 70)
    print("10. BRAND ANALYSIS")
    print("=" * 70)

    if "Brand" not in df.columns:

        print(
            "Brand column not available."
        )

        return

    brand_df = df[
        df["Brand"].notna()
    ].copy()

    if brand_df.empty:

        print(
            "No brand data available."
        )

        return

    # 
    # Create normalized brand
    # 

    brand_df["Brand_Normalized"] = (
        brand_df["Brand"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    # 
    # Brand summary by category
    # 

    brand_summary = (
        brand_df
        .groupby(
            [
                "Category",
                "Brand_Normalized"
            ]
        )
        .agg(

            Product_Count=(
                "Product Name",
                "count"
            ),

            Total_Price=(
                "Price",
                "sum"
            ),

            Total_Original_Price=(
                "Original Prices",
                "sum"
            ),

            Total_Discount=(
                "Discount_Amount",
                "sum"
            ),

            Average_Price=(
                "Price",
                "mean"
            ),

            Average_Discount=(
                "Discount rates",
                "mean"
            )
        )
        .reset_index()
        .round(2)
    )

    print(
        "\nBrand Summary:"
    )

    print(
        brand_summary.head(30)
    )

    brand_summary.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "brand_category_summary.csv"
        ),
        index=False
    )

    # 
    # Top brands by product count
    # 

    top_brands = (
        brand_df[
            "Brand_Normalized"
        ]
        .value_counts()
        .head(15)
        .sort_values()
    )

    print(
        "\nTop 15 Brands by Product Count:"
    )

    print(top_brands)

    # 
    # Visualization 15
    # 

    plt.figure(figsize=(10, 7))

    plt.barh(
        top_brands.index,
        top_brands.values
    )

    plt.title(
        "Top 15 Brands by Number of Products"
    )

    plt.xlabel(
        "Number of Products"
    )

    plt.ylabel("Brand")

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "15_top_brands.png"
        ),
        dpi=300
    )

    plt.show()

    # 
    # Top brands by average discount
    # Minimum 10 products
    # 

    top_discount_brands = (
        brand_df
        .groupby(
            "Brand_Normalized"
        )["Discount rates"]
        .agg(
            [
                "mean",
                "count"
            ]
        )
        .query(
            "count >= 10"
        )
        .sort_values(
            "mean"
        )
        .tail(15)
    )

    print(
        "\nBrands with Highest Average Discount:"
    )

    print(
        top_discount_brands.round(2)
    )

    # 
    # Visualization 16
    # 

    plt.figure(figsize=(10, 7))

    plt.barh(
        top_discount_brands.index,
        top_discount_brands["mean"]
    )

    plt.title(
        "Brands with Highest Average Discount\n"
        "(Minimum 10 Products)"
    )

    plt.xlabel(
        "Average Discount (%)"
    )

    plt.ylabel("Brand")

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "16_top_discount_brands.png"
        ),
        dpi=300
    )

    plt.show()



# 14. PRICE BAND ANALYSIS


def price_band_analysis(df):

    print("\n")
    print("=" * 70)
    print("11. PRICE BAND ANALYSIS")
    print("=" * 70)

    bins = [
        -np.inf,
        500,
        1000,
        5000,
        10000,
        25000,
        50000,
        100000,
        np.inf
    ]

    labels = [
        "<=₹500",
        "₹501–₹1,000",
        "₹1,001–₹5,000",
        "₹5,001–₹10,000",
        "₹10,001–₹25,000",
        "₹25,001–₹50,000",
        "₹50,001–₹1,00,000",
        ">₹1,00,000"
    ]

    df["Price_Band"] = pd.cut(
        df["Price"],
        bins=bins,
        labels=labels
    )

    band_summary = (
        df.groupby(
            [
                "Category",
                "Price_Band"
            ],
            observed=True
        )
        .size()
        .reset_index(
            name="Product_Count"
        )
    )

    print(
        "\nPrice Band by Category:"
    )

    print(band_summary)

    band_summary.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "price_band_category.csv"
        ),
        index=False
    )

    # 
    # Overall price-band distribution
    # 

    band_total = (
        df["Price_Band"]
        .value_counts()
        .reindex(labels)
        .fillna(0)
    )

    print(
        "\nOverall Price Band Distribution:"
    )

    print(band_total)

    # 
    # Visualization 17
    # 

    plt.figure(figsize=(12, 6))

    plt.bar(
        band_total.index,
        band_total.values
    )

    plt.title(
        "Product Distribution Across Price Bands"
    )

    plt.xlabel(
        "Price Band"
    )

    plt.ylabel(
        "Number of Products"
    )

    plt.xticks(
        rotation=35,
        ha="right"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_FOLDER,
            "17_price_band_distribution.png"
        ),
        dpi=300
    )

    plt.show()



# 15. DYNAMIC PRODUCT SEARCH


def find_products(
    df,
    category="laptops",
    max_price=50000,
    min_rating=4,
    min_discount=10
):

    print("\n")
    print("=" * 70)
    print("12. DYNAMIC PRODUCT SEARCH")
    print("=" * 70)

    data = df.copy()

    # Category condition
    condition = (
        data["Category"]
        .astype(str)
        .str.lower()
        .eq(category.lower())
    )

    # Price condition
    condition &= (
        data["Price"] < max_price
    )

    # Rating condition
    if "Ratings" in data.columns:

        condition &= (
            data["Ratings"] > min_rating
        )

    # Discount condition
    condition &= (
        data["Discount rates"]
        > min_discount
    )

    result = data.loc[
        condition
    ].copy()

    columns = [
        "Product Name",
        "Category",
        "Brand",
        "Price",
        "Original Prices",
        "Discount rates",
        "Ratings"
    ]

    columns = [
        column
        for column in columns
        if column in result.columns
    ]

    result = result[
        columns
    ].sort_values(
        by="Price"
    )

    print(
        f"Category       : {category}"
    )

    print(
        f"Maximum Price  : ₹{max_price:,.0f}"
    )

    print(
        f"Minimum Rating : {min_rating}"
    )

    print(
        f"Minimum Discount: {min_discount}%"
    )

    print(
        f"\nProducts Found: {len(result)}"
    )

    print(
        result.head(20)
    )

    result.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "dynamic_product_search.csv"
        ),
        index=False
    )

    return result



# 16. CATEGORY + BRAND DETAILED ANALYSIS


def category_brand_analysis(df):

    print("\n")
    print("=" * 70)
    print("13. CATEGORY + BRAND ANALYSIS")
    print("=" * 70)

    if "Brand" not in df.columns:
        return

    data = df[
        df["Brand"].notna()
    ].copy()

    data["Brand_Normalized"] = (
        data["Brand"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    summary = (
        data.groupby(
            [
                "Category",
                "Brand_Normalized"
            ]
        )
        .agg(

            Product_Count=(
                "Product Name",
                "count"
            ),

            Total_Price=(
                "Price",
                "sum"
            ),

            Total_Original_Price=(
                "Original Prices",
                "sum"
            ),

            Total_Discount=(
                "Discount_Amount",
                "sum"
            ),

            Average_Discount=(
                "Discount rates",
                "mean"
            )
        )
        .reset_index()
    )

    # Overall discount based on total prices
    summary["Discount_Rate"] = np.where(
        summary["Total_Original_Price"] > 0,

        (
            summary["Total_Discount"]
            /
            summary["Total_Original_Price"]
        ) * 100,

        np.nan
    )

    summary = summary.round(2)

    print(
        "\nCategory + Brand Summary:"
    )

    print(
        summary.head(50)
    )

    summary.to_csv(
        os.path.join(
            OUTPUT_FOLDER,
            "category_brand_detailed.csv"
        ),
        index=False
    )



# 17. BUSINESS INSIGHTS


def business_insights(
    df,
    category_summary
):

    print("\n")
    print("=" * 70)
    print("14. BUSINESS INSIGHTS")
    print("=" * 70)

    # Highest average price
    highest_avg_price = (
        category_summary
        .loc[
            category_summary[
                "Average_Price"
            ].idxmax()
        ]
    )

    # Highest median price
    highest_median_price = (
        category_summary
        .loc[
            category_summary[
                "Median_Price"
            ].idxmax()
        ]
    )

    # Highest discount
    highest_discount = (
        category_summary
        .loc[
            category_summary[
                "Average_Discount"
            ].idxmax()
        ]
    )

    # Lowest discount
    lowest_discount = (
        category_summary
        .loc[
            category_summary[
                "Average_Discount"
            ].idxmin()
        ]
    )

    # Highest product count
    highest_product_count = (
        category_summary
        .loc[
            category_summary[
                "Product_Count"
            ].idxmax()
        ]
    )

    print(
        "\nKey Findings:"
    )

    print(
        f"""
1. Highest average selling price:
   {highest_avg_price['Category']}
   ₹{highest_avg_price['Average_Price']:,.2f}

2. Highest median selling price:
   {highest_median_price['Category']}
   ₹{highest_median_price['Median_Price']:,.2f}

3. Highest average discount:
   {highest_discount['Category']}
   {highest_discount['Average_Discount']:.2f}%

4. Lowest average discount:
   {lowest_discount['Category']}
   {lowest_discount['Average_Discount']:.2f}%

5. Largest product catalog:
   {highest_product_count['Category']}
   {highest_product_count['Product_Count']:,} products
"""
    )

    # Rating insights
    if "Ratings" in df.columns:

        rated = df.dropna(
            subset=["Ratings"]
        )

        if not rated.empty:

            rating_by_category = (
                rated.groupby(
                    "Category"
                )["Ratings"]
                .mean()
                .sort_values(
                    ascending=False
                )
            )

            print(
                "\nAverage Rating by Category:"
            )

            print(
                rating_by_category.round(2)
            )

    print(
        "\nImportant Interpretation Notes:"
    )

    print(
        "- Product count represents catalog listings, "
        "not sales volume."
    )

    print(
        "- Listed discount does not directly represent "
        "seller profit."
    )

    print(
        "- Ratings are available only for categories "
        "where the source dataset contains them."
    )

    print(
        "- High price does not automatically mean "
        "high profitability."
    )

    print(
        "- Outliers should be investigated rather than "
        "automatically removed."
    )



# 18. EXPORT FINAL ANALYSIS DATA


def export_final_data(df):

    output_file = os.path.join(
        OUTPUT_FOLDER,
        "analysis_ready_data.csv"
    )

    df.to_csv(
        output_file,
        index=False
    )

    print(
        f"\nAnalysis-ready dataset saved to:\n"
        f"{output_file}"
    )



# 19. MAIN FUNCTION


def main():

    print("\n")
    print("=" * 70)
    print("FLIPKART PRODUCT ANALYSIS")
    print("=" * 70)

    
    # Load
    

    df = load_data()

    
    # Basic overview
    

    dataset_overview(df)

    
    # Data quality
    

    data_quality_analysis(df)

    
    # Category analysis
    

    category_summary = category_analysis(
        df
    )

    
    # Price analysis
    

    price_analysis(
        df
    )

    
    # Discount analysis
    

    discount_analysis(
        df
    )

    
    # Price + discount relationship
    

    price_discount_relationship(
        df
    )

    
    # Outlier analysis
    

    outlier_analysis(
        df
    )

    
    # Rating analysis
    

    rating_analysis(
        df
    )

    
    # Correlation analysis
    

    correlation_analysis(
        df
    )

    
    # Brand analysis
    

    brand_analysis(
        df
    )

    
    # Category + Brand
    

    category_brand_analysis(
        df
    )

    # Price bands
   

    price_band_analysis(
        df
    )

    
    # Dynamic product search
    

    find_products(
        df,
        category="laptops",
        max_price=50000,
        min_rating=4,
        min_discount=10
    )

    
    # Business insights
    

    business_insights(
        df,
        category_summary
    )

   
    # Export
    

    export_final_data(
        df
    )

    
    # Finished
    

    print("\n")
    print("=" * 70)
    print("ANALYSIS COMPLETED SUCCESSFULLY")
    print("=" * 70)

    print(
        f"\nAll analysis files are available in:"
    )

    print(
        os.path.abspath(
            OUTPUT_FOLDER
        )
    )



# 20. RUN


if __name__ == "__main__":
    main()